youngstar/youngstar/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ysapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

youngstar/ysapp/urls.py
from django.urls import path
from . import views
app_name = 'ysapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('person/<int:person_id>/', views.detail, name='detail'),
    path('add/', views.add_person, name='add_person'),



]

youngstar/ysapp/models.py
from django.db import models


# Create your models here.
class movie(models.Model):
    name = models.CharField(max_length=100)
    house_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10)
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

youngstar/ysapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import movie


# Create your views here.
def index(request):
    person = movie.objects.all()
    context = {'person': person}
    return render(request, 'index.html', context)


def detail(request, person_id):
    person = movie.objects.get(id=person_id)
    return render(request, 'detail.html', {'person': person})


def add_person(request):
    if request.method == "POST":
        name = request.POST.get('name',)
        house_name = request.POST.get('house_name', )
        phone_number = request.POST.get('phone_number', )
        img = request.FILES['img']
        person = movie(name=name, house_name=house_name, phone_number=phone_number, img=img)
        person.save()
    return render(request, 'add.html')


def regi(request, person_id):
    person = movie.objects.get(id=person_id)
    return render(request, 'register.html', {'person': person})

youngstar/templates/add.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="margin-top:30px;">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Your Name">
    <input type="text" name="house_name" placeholder="Enter Your House Name">
    <input type="text" name="phone_number" placeholder="Enter Your PhoneNumber ">
    <input type="file" name="img" >
    <input type="submit">

</form>

</div>

<div class="container"  style="margin-top:30px;">
    <h2>Please submit your details <br>We will contact you soon<br>for confirmation</h2>
</div>
<div class="container" style="margin-top:30px;"><a href="{% url 'ysapp:index' %}"><button type="button" class="btn btn-primary" > Back</button></a></div>
{% endblock %}

youngstar/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ml">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      YOUNGSTAR Puthentheru
  </a>

</nav>


{% block body %}
{% endblock %}
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
</body>
</html>

youngstar/templates/detail.html
{% extends 'base.html' %}
{% block body %}

 {{person.name}} Successfully registered <br>
Token Number : {{person.id}}<br>
House Name : {{person.house_name}}<br>
Phone : **********
<!--{{person.phone_number}}<br>-->
<!--<img src="{{person.img.url}}" width="100" height="100">-->

{% endblock %}}

youngstar/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container" style="margin-top:20px;">

    <h1>YOUNGSTAR ONAM REGISTRATION POOKKALA-MATHSARAM </h1>
     <a href="{% url 'ysapp:add_person' %}"><button type="button" class="btn btn-primary" > Register</button></a>
</div>
<div class="container" style="margin-top:20px;">
{% for i in person %}
<img src="{{i.img.url}}" width="100" height="100">
<a href="{% url 'ysapp:detail' i.id %}"> {{i.name}}</a>
{% endfor %}
</div>
{% endblock %}

youngstar/templates/register.html
 {% extends 'base.html' %}
{% block body %}

 {{person.name}} Successfully registered <br>
Token Number : {{person.id}}<br>
House Name : {{person.house_name}}<br>
Phone : **********
<!--{{person.phone_number}}<br>-->
<!--<img src="{{person.img.url}}" width="100" height="100">-->

{% endblock %}}